export const PAYSLIP_LETTER_EMPLYEES = [
  {
    employeeName: "Ankit Sharma",
    employeeDesignation: "Software Engineer",
    employeeDepartment: "CSC",
    employeeId: "woodrock-1",
    basicSalary: 45000,
    houseRentAllowance: 10000,
    conveyanceAllowance: 3000,
    training: 1000,
    grossSalary: 59000,
    netPay: 55000,
    salaryOfEmployee: 59000,
    totalWorkingDays: 30,
    totalPresentDays: 28,
    totalAbsent: 2,
    OT:12,
    incentives:123,
    uninformedLeaves: 0,
    halfDay: 1,
    calculatedSalary: 55000,
    month: "January",
    year: 2025,
    professionalTax: 1000,
    totalDeductions: 4000,
    employeeEmail: "ankit.sharma@example.com",
    dateOfPayment: "2025-07-01",
  },
  {
    employeeName: "Priya Desai",
    employeeDesignation: "HR Manager",
    basicSalary: 60000,
    houseRentAllowance: 15000,
    conveyanceAllowance: 4000,
    training: 2000,
    grossSalary: 81000,
    netPay: 77000,
    salaryOfEmployee: 81000,
    totalWorkingDays: 30,
    totalPresentDays: 30,
    totalAbsent: 0,
    uninformedLeaves: 0,
    halfDay: 0,
    calculatedSalary: 77000,
    month: "January",

    OT:12,
    incentives:123,
    year: 2025,
    professionalTax: 1000,
    totalDeductions: 4000,
    employeeEmail: "priya.desai@example.com",
    dateOfPayment: "2025-07-01",
    employeeDepartment: "CSC",
    employeeId: "woodrock-2",
  },
  {
    employeeName: "Ravi Patel",
    employeeDesignation: "Accountant",
    basicSalary: 35000,
    houseRentAllowance: 8000,
    conveyanceAllowance: 2500,
    training: 500,
    grossSalary: 46000,
    netPay: 42000,
    salaryOfEmployee: 46000,
    totalWorkingDays: 30,
    totalPresentDays: 26,
    totalAbsent: 4,
    uninformedLeaves: 1,
    halfDay: 2,
    calculatedSalary: 42000,
    month: "January",

    OT:12,
    incentives:123,
    year: 2025,
    professionalTax: 1000,
    totalDeductions: 4000,
    employeeEmail: "ravi.patel@example.com",
    dateOfPayment: "2025-07-01",
    employeeDepartment: "CSC",
    employeeId: "woodrock-3",
  },
];
